import datetime
import psycopg2
from passlib.hash import pbkdf2_sha256

from contextlib import closing

from flask import Flask
from flask import g
from flask import render_template
from flask import abort
from flask import request
from flask import url_for
from flask import redirect
from flask import session

from models import Post, update_entry, write_entry, get_all_entries, get_one_entry
# -*- coding: utf-8 -*-


# add this just below the SQL table definition we just created
app = Flask(__name__)
app.config['DEBUG'] = True


######################
# THE VIEW FUNCTIONS #
######################

@app.route('/')
def show_entries():
    entries = get_all_entries()
    return render_template('list_entries.html', entries=entries)


@app.route('/add', methods=['POST'])
def add_entry():
    try:
        Post.write_entry(title=request.form['title'], body=request.form['text'])

    except psycopg2.Error:
        # this will catch any errors generated by the database
        abort(500)
    return redirect(url_for('show_ajax'))


@app.route('/<int:entryID>', methods=['GET'])
def view_entry(entryID=None):

    entry = Post.get_one_entry(entryID)
    # print entry
    return render_template('entry.html', entry=entry)


@app.route('/edit/<int:entryID>', methods=['GET'])
def edit_entry(entryID=None):

    entry = Post.get_one_entry(entryID)
    # print entry
    return render_template('edit.html', entry=entry)


@app.route('/update', methods=['POST'])
def update(entryID=None):

    entryID = entryID
    print entryID
    try:
        title = request.form['title']
        text = request.form['text']
        Post.update_entry(title, text, entryID)
    except psycopg2.Error:
        # this will catch any errors generated by the database
        abort(500)
    return redirect(url_for('show_entries'))


